### ISSUE TITLE
Из-за проблем с подключением файлы не загружаются. Как увеличить время ожидания и количество попыток?

### ISSUE THREAD

**Issue by vsile** [rendrom/rosreestr2coord#13]
```
user@c107 ~/pythonserver $ python rosreestr2coord/rosreestr2coord.py -c 23:01:0000000:544
Press Ctrl+C to exit
Start downloading area info: http://pkk5.rosreestr.ru/api/features/1/23:1:0:544
Area info downloaded.
Run tiles download:
58% 7/12
Downloading completed. Uploaded tiles - 7

user@c107 ~/pythonserver $ python rosreestr2coord/rosreestr2coord.py -c 23:01:0000000:544
Press Ctrl+C to exit
Start downloading area info: http://pkk5.rosreestr.ru/api/features/1/23:1:0:544
Area info downloaded.
Run tiles download:
75% 9/12
Downloading completed. Uploaded tiles - 9
```
WARNING:scripts.logger:[Errno 104] Connection reset by peer
WARNING:scripts.logger:
WARNING:scripts.logger:[Errno 104] Connection reset by peer
WARNING:scripts.logger:
WARNING:scripts.logger:[Errno 104] Connection reset by peer
WARNING:scripts.logger:Waiting time exceeded

Из-за проблем с подключением файлы не загружаются. Как увеличить время ожидания и количество попыток?

**Comment by vsile** [comment]
Или как игнорировать уже загруженные файлы, чтобы их больше не загружать?
В директории tmp в соответствующем каталоге я вижу 12 из 12 изображений. Но из-за того, что каждый раз связь прерывается, сформировать одно изображение из 12 кусочков скрипт не может..

**Comment by rendrom** [comment]
самое быстрое решение, это попробовать добавить к запросу -P
```bash
python rosreestr2coord/rosreestr2coord.py -c 23:01:0000000:544 -P
```
для того чтобы повторно не скачивались кусочки нужно будет дорабатывать скрипт, в планах

**Comment by TSA21432** [comment]
для того чтобы повторно не скачивались кусочки нужно будет дорабатывать скрипт, в планах
планы остались планами?

**Comment by rendrom** [comment]
> для того чтобы повторно не скачивались кусочки нужно будет дорабатывать скрипт, в планах
> планы остались планами?

наконец-то удалось реализовать
