### ISSUE TITLE
перекодировка текста

### ISSUE THREAD

**Issue by TSA21432** [rendrom/rosreestr2coord#14]
если запускать с атрибутом -a - добавлять атрибуты участка к параметрам GeoJSON файла
то в файл попадает текст в формате utf16  переделать в utf8 или ANSI

 возможно я путаю с кодировкой но в файле такое  \u0443\u043b \u0417\u0432\u0451\u0437\u0434\u043d\u0430\u044f, \u0434 14

**Comment by denny123** [comment]
у меня тоже самое, я результат просто вывожу на сайт с кодировкой utf-8 и все кажет норм, поэтому не обращал внимания.

**Comment by TSA21432** [comment]
Как долго ждать исправления?

a = u'1a'
a = a.decode('utf-8').encode('cp1251') 
print a

a = u'1\u0430'
a = a.encode('UTF-8').decode('UTF-8').encode('cp1251')
print a

**Comment by rendrom** [comment]
пробовал, но пока не получилось

**Comment by rendrom** [comment]
Исправлено в новой версии

**Comment by TSA21432** [comment]
а в .geojson больше не выводится?

**Comment by rendrom** [comment]
Выводится, почему нет? Есть проблемы?

**Comment by TSA21432** [comment]
в папке сохраняются только 5 файлов 2 json, 3 png/
может что не так делаю.
..rosreestr2coord-master>python rosreestr2coord.py -c 30:05:210101:220 -t5 -d

если не так подскажите как
