### ISSUE TITLE
улучшение 

### ISSUE THREAD

**Issue by TSA21432** [rendrom/rosreestr2coord#15]
Предлагаю добавить сбор информации для последующей обработки в cadastral_numbers_list.txt

например:
22 Алтайский краевой
в нем округа 22:01 по 58 вроде
у этих огругов свои участки
https://pkk5.rosreestr.ru/api/features/1?text=%D0%92%20%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0%D1%85%20%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B0%2022:41&tolerance=4097&limit=10000&sqo=22:41&sqot=3&callback=jQuery191007954587202508434_1550080182060&_=1550080182071
и так все вложения
как матрешка ;-)
т.е. мне нужно например в в этом квартале 22:34:010813 все участки и ОКС
https://pkk5.rosreestr.ru/api/features/1?text=%D0%92%20%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0%D1%85%20%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%B0%2022:34:10813&tolerance=16&limit=11&sqo=22:34:10813&sqot=2&callback=jQuery191007954587202508434_1550080182060&_=1550080182084

https://pkk5.rosreestr.ru/api/features/5?text=%D0%92%20%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0%D1%85%20%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%B0%2022:34:10813&tolerance=16&limit=11&sqo=22:34:10813&sqot=2&callback=jQuery191007954587202508434_1550080182060&_=1550080182086

**Comment by rendrom** [comment]
Спасибо за предложение, но сначала нужно переработать систему кэширования тайлов и ведение каталога, а то много ошибок вываливается, не получается нормально работать с большим набором участков

**Comment by TSA21432** [comment]
ну я смотрю не так часто вы занимаетесь утилитой. ;-)

**Comment by rendrom** [comment]
она сейчас в таком состоянии что очень много надо переписать, никак не соберусь

**Comment by TSA21432** [comment]
я то думал от идеи до воплощения один шаг. Хотя гениям нужно вдохновение...
будем ждать

**Comment by rendrom** [comment]
гении это ребята которые разрабатывабт OpenCV

**Comment by TSA21432** [comment]
возможно добавить запрос? вида

https://pkk5.rosreestr.ru/api/features/1?text=%D0%92%20%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0%D1%85%20%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B0%2016:56&tolerance=256&limit=11&sqo=16:56&sqot=3&callback=jQuery19106633388216196459_1571515804617&_=1571515804628

подмена 16:56 в двух  местах ответ в текст (раньше сайт отдавал теперь не хочет
  спасибо!!!

**Comment by rendrom** [comment]
Данное улучшение не планируется. Только если кто пришлёт PR
