### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by brat50** [rendrom/rosreestr2coord#16]
Вот такая ошибка когда пытаюсь использовать с параметром -d
```
C:\Users\Acer>rosreestr2coord -d -c 23:18:0701000:42
Press Ctrl+C to exit
Run tiles download:
100% 6/6
Downloading completed. Uploaded tiles - 6
Merging tiles...
You raster - C:\Users\Acer\tmp\23_18_701000_42.png
23:18:0701000:42 - restored from C:\Users\Acer\catalog.json
C:\Users\Acer\output\geojson\23_18_0701000_42.geojson
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\rosreestr2coord.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\scripts\console.py", line 128, in main
    _main()
  File "c:\python27\lib\site-packages\scripts\console.py", line 97, in _main
    get_by_code(code, path, area_type, catalog_path, with_attrs, epsilon, coord_out, output, display, center_only, with_proxy=opt.proxy)
  File "c:\python27\lib\site-packages\scripts\console.py", line 117, in get_by_code
    area.show_plot()
  File "c:\python27\lib\site-packages\scripts\parser.py", line 387, in show_plot
    for x, y in corners:
ValueError: too many values to unpack
```

**Comment by rendrom** [comment]
ого, про этот режим забыл вообще. Использовался в самом начале для отладки. Надо попробовать его восстановить или удалить вообще эту опцю.

**Comment by brat50** [comment]
Вообще вам большое спасибо. Честно говоря это первое приложение которое просто и понятно даёт координаты участка. Всё в командной строке, без танцев с бубном. 

Мне бы очень хотелось иметь dll библиотеку с функцией, которая вернёт мне координаты участка. Использовать функцию буду из приложения написанного на Lazarus. Я не знаю возможностей Питона и может ли он делать dll для использования под windows, да мне и некогда разбираться. Можете ли сделать это вы за вознаграждение? Детали можем обсудить в личной переписке.

**Comment by rendrom** [comment]
Исправлена ошибка с отображением диаграммы
![image](https://user-images.githubusercontent.com/1478481/78774336-1d955480-79c7-11ea-9e7a-8a7b83077c33.png)
