### ISSUE TITLE
Координаты кадастрового квартала

### ISSUE THREAD

**Issue by 62anton** [rendrom/rosreestr2coord#18]
Подскажите, можно ли загрузить координы кадастрового квартала? Если можно то как это сделать?

**Comment by rendrom** [comment]
`python .\rosreestr2coord.py -c 38:36:000033 -t 2`
Используйте -P чтобы пропускать запросы через прокчи
`python .\rosreestr2coord.py -c 38:36:000033 -t 2 -P`

Готовый проект с точными координатами как в выписке можете заказать тут https://data.nextgis.com/ru/cadastre/

**Comment by 62anton** [comment]
Огромное спасибо, за оперативный ответ. А есть ли возможность получить координаты в МСК?


>Пятница, 22 марта 2019, 6:52 +03:00 от Artemiy <notifications@github.com>:
>
>python .\rosreestr2coord.py -c 38:36:000033 -t 2
>Используйте -P чтобы пропускать запросы через прокчи
>python .\rosreestr2coord.py -c 38:36:000033 -t 2 -P
>Готовый проект с точными координатами как в выписке можете заказать тут  https://data.nextgis.com/ru/cadastre/
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Yu An

**Comment by rendrom** [comment]
если выполнить инструкцию https://github.com/rendrom/rosreestr2coord/wiki/Instruction пункт 8 и запустить GUI
`python gui.py`
то там будет возможность изменять координатные системы, но интерфейс только для участков

**Comment by rendrom** [comment]
По ссылке выше есть данные и в мск и в wgs
