### ISSUE TITLE
Ошибка при запуске gui.py

### ISSUE THREAD

**Issue by 62anton** [rendrom/rosreestr2coord#19]
При запуске gui.py и указании номера участка, программа зависает. На втором экране висит надпись "Start downloading area info: http://pkk5.rosreestr.ru/api/features/1/47:16:65000
2:317" и ничего не грузится. Может поменялась форма запроса?

**Comment by TSA21432** [comment]
Да! давно поменялось все. и теперь эта строка просто так не работает. так что лавочку прикрыли.

**Comment by denny123** [comment]
те данный скрипт не актуален?

**Comment by TSA21432** [comment]
ну если автор как то сделает то возможно, а прямой ответ прикрыт...

**Comment by denny123** [comment]
http://gis-lab.info/forum/viewtopic.php?style=1&f=2&t=20958&start=90
TLS 1.2 - не он виновник?

**Comment by rendrom** [comment]
GUI удален в текущей версии, планируется замена на вебсервер
