### ISSUE TITLE
Перестало работать

### ISSUE THREAD

**Issue by denny123** [rendrom/rosreestr2coord#20]
На данный момент не получает данные с росреестра или долго грузит. Пробовал через прокси в том числе. Может ктонить проверит и скажет робит счас или нет?

**Comment by rendrom** [comment]
Сам давно не проверял.
Заметил что есть форки:
https://github.com/rendrom/rosreestr2coord/network/members

Вот в этом, судя по коммитам, решают проблему с запросами к росреестру.
Предлагаю попробовать запустить его. Если будет работать, можете написать автору чтобы он сдела Pull Request

**Comment by denny123** [comment]
Работает, но попробовал в винде. На прежнем линуксе, где я всегда запускал более не хочет получать данные(прокси в том числе). Не пробовал оригинальный скрипт в винде, только alukyano.

**Comment by botanegg** [comment]
Запустил 2to3, поправил пару мест с питонокодировками...

Затем пустил всё по https и добавил следующие хедеры
```
'x-requested-with': 'XMLHttpRequest',
'pragma': 'no-cache',
'referer': 'https://pkk5.rosreestr.ru/'
```

Всё работает :)

**Comment by botanegg** [comment]
Извиняюсь за внезапное исчезновение :)
Не думаю что я всё хорошо сделал (там же портирование с 2 на 3 питон, куча варнингов и прочего)

Постараюсь всё исправить на 2ой версии, и тогда зашлю PR
основное изменение это:
```
                headers = {
                    'x-requested-with': 'XMLHttpRequest',
                    'pragma': 'no-cache',
                    'user-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36',
                    'referer': 'https://pkk5.rosreestr.ru/'}
```
