### ISSUE TITLE
Вебсервер с UI для поиска координат

### ISSUE THREAD

**Issue by rendrom** [rendrom/rosreestr2coord#25]

**Comment by TSA21432** [comment]
в *.geojson как выводить или не будет. Спасибо!!!

**Comment by rendrom** [comment]
geojson, как и раньше, сохраняется после выполнения скрипта из консоли. В UI планируется кнопка для сохранения результата

**Comment by TSA21432** [comment]
в папке сохраняются только 5 файлов 2 json, 3 png/
может что не так делаю.
..rosreestr2coord-master>python rosreestr2coord.py -c 30:05:210101:220 -t5 -d

если не так подскажите как
