### ISSUE TITLE
Почему не пользуете download_feature_info в чистом виде?

### ISSUE THREAD

**Issue by Hedgehogues** [rendrom/rosreestr2coord#27]
Привет. Зачем использовать парсинг картинок, когда есть download_feature_info (в конструкторе Area функция)? Там все координаты приезжают. Кажется этого достаточно.

**Comment by rendrom** [comment]
Из этого запроса можно получить только extent и center

![image](https://user-images.githubusercontent.com/1478481/80240451-6e2dd280-8694-11ea-9ecc-eaf5900b6a26.png)
