### ISSUE TITLE
Что такое areatype?

### ISSUE THREAD

**Issue by Hedgehogues** [rendrom/rosreestr2coord#28]
Что такое areatype?

**Comment by rendrom** [comment]
![image](https://user-images.githubusercontent.com/1478481/80240758-01ff9e80-8695-11ea-95cd-ba4939006097.png)

в запросе
python -m rosreestr2coord -c 77:01:0002002:1032 -t 5 -P

![image](https://user-images.githubusercontent.com/1478481/80241441-2dcf5400-8696-11ea-9e25-3834b62f0306.png)
 

-t - тип площади:
1 - Участки
2 - Кварталы
3 - Районы
4 - Округа
5 - ОКС
6 - Тер. зоны; 7 - Границы; 9 - ГОК; 10 - ЗОУИТ; 12 - Лес; 13 - Красные линии; 15 - СРЗУ; 16 - ОЭЗ 16
