### ISSUE TITLE
поддержка учётных номеров ЗОУИТ

### ISSUE THREAD

**Issue by alexandervlpl** [rendrom/rosreestr2coord#29]
Спасибо за отличный проект! Какой только фигнёй нам не приходится страдать, чтобы получить "публичные" ГИС данные в нормальном формате. :roll_eyes: 

К сожалению скрипт не парсит учётные номера ЗОУИТ в формате **50.00.2.1152**. Пробовал так: `rosreestr2coord -c 50.00.2.1152 -t 10`. Вот [сам объект](https://pkk.rosreestr.ru/#/search/56.28568672816339,37.129639328599396/11/@qih8n8v9?text=56.323299%2037.064479&type=10&inPoint=true&opened=50.00.2.1152) в ПКК.

Интересуют границы ООПТ (нацпарков, заказников) в том числе для внесения в OpenStreetMap.

**Comment by rendrom** [comment]
да, по ЗОУИТ  нужно реализовать дополнительную логику

**Comment by rendrom** [comment]
Теперь стало возможно парсить учётные номера ЗОУИТ в формате 50.00.2.1152

`rosreestr2coord -m -c 50.00.2.1152 -t 10 -P`
 
![image](https://user-images.githubusercontent.com/1478481/80780890-1cf57580-8ba3-11ea-966d-8d3ed90cfbff.png)

В текущей версии есть проблема с производительностью, очень долго может выполняться склеивание тайлов (https://github.com/rendrom/rosreestr2coord/issues/30) и потребуется 64 разрядная версия python.

**Comment by alexandervlpl** [comment]
Это реально круто. Огромное спасибо за такую работу!
