### ISSUE TITLE
Конвертация происходит, но geojson не производится

### ISSUE THREAD

**Issue by simgislab** [rendrom/rosreestr2coord#3]
>python rosreestr2coord.py -c 23:49:0512002:5409

Подозреваю, что дело в форме ![исходного](http://pkk5.rosreestr.ru/#x=4491404.363955449&y=5410969.5875690505&z=20&text=23%3A49%3A0512002%3A5409&type=1&app=search&opened=1) полигона. 

Не уверен так же, что если результат нельзя произвести, то стоит добавлять его в catalog.json

**Comment by rendrom** [comment]
В каталог ещё и атрибуты пишутся. С ключом -r каталог не будет использоваться. 
Что касается участков такого типа, буду разбираться почему не извлекается геометрия.

**Comment by rendrom** [comment]
Можно подобать точность аппроксимации через -e
 
```python rosreestr2coord.py -c 23:49:0512002:5409 -e 0.1```

![screen shot 2017-05-19 at 23 55 27](https://cloud.githubusercontent.com/assets/1478481/26256581/027069c2-3cf0-11e7-8509-e8f8e1b69c47.png)

**Comment by simgislab** [comment]
работает, спасибо
