### ISSUE TITLE
Оптимизировать склеивание тайлов

### ISSUE THREAD

**Issue by rendrom** [rendrom/rosreestr2coord#30]
Сейчас процесс склеивания изображения из большого числа тайлов требует много компьютерных ресурсов.

https://github.com/rendrom/rosreestr2coord/blob/c19536ed68b5f6ee218f51425dfb3af3703384b6/rosreestr2coord/merge_tiles.py#L422

Нужно выполнить оптимизацию этого процесса.

**Comment by alexandervlpl** [comment]
Попробую заняться этим на следующей неделе? Потребление памяти тоже впечатляет, у кого-то может и на хватить. :fearful:

**Comment by rendrom** [comment]
Да, будет здорово.
Пока такие идеи:
- всё-таки разобраться как делать большой растр с меньшим потреблением памяти (не получилось найти способ).
- уменьшать размер тайлов. Может привести к потере и без того плохого качества распознавания.
- распознавать каждый тайл а потом склеивать в один geojson сторонними библиотеками (много переделывать).

**Comment by alexandervlpl** [comment]
> всё-таки разобраться как делать большой растр с меньшим потреблением памяти (не получилось найти способ).

Способ возможно нашёл, только потестить пока не могу. ПКК даже на пинг не отвечает, видимо сервер включат уже после праздников. :laughing:

**Comment by rendrom** [comment]
Не, там всё гораздо хуже. Не проходят запросы за тайлами типа `https://pkk.rosreestr.ru/arcgis/rest/services/PKK6/CadastreSelected/MapServer/export?...` (в браузере открываются).

Скорее всего новое ограничение росреестра. Пока добавил проверки чтобы ответ с ошибкой не кэшировался 

https://github.com/rendrom/rosreestr2coord/blob/64dbd55545e728577bd01d611644c111e7383ce2/rosreestr2coord/utils.py#L119

но нужно придумать теперь как формировать валидные запросы
