### ISSUE TITLE
Ошибки при запросе к тайлам

### ISSUE THREAD

**Issue by rendrom** [rendrom/rosreestr2coord#32]
Не проходят запросы к тайлам типа `https://pkk.rosreestr.ru/arcgis/rest/services/PKK6/CadastreSelected/MapServer/export?...` (в браузере открываются).

Скорее всего новое ограничение росреестра. Пока добавил проверки чтобы ответ с ошибкой не кэшировался 

https://github.com/rendrom/rosreestr2coord/blob/64dbd55545e728577bd01d611644c111e7383ce2/rosreestr2coord/utils.py#L119

но нужно придумать теперь как формировать валидные запросы

**Comment by alexandervlpl** [comment]
Странно, у меня по прежнему даже в браузере ничего не открывается (через прокси тоже). Включая основной сайт `https://pkk.rosreestr.ru`. Пока похоже что сторож включил кипятильник и в серверной комнате выбило пробки. ;) Посмотрим что будет завтра.

Конечно возможно что они добавили CORS или что-нибудь сложнее для ограничения трафика.

**Comment by rendrom** [comment]
У меня прямо сейчас https://pkk.rosreestr.ru/ работает без прокси и тора. Можно подождать, но скорее всего придётся модифицировать скрипт формирования запросов.

**Comment by rendrom** [comment]
а вот сейчас скрипт заработал

**Comment by alexandervlpl** [comment]
Выяснилось, что ПКК блочит многие адреса моего оператора. А также прокси и туннели которые я пробовал, и многие выходы тора. Опция `-P` тут тоже не помогла. Сейчас установил себе новый VPN сервер, через него пока всё работает.
