### ISSUE TITLE
Формат KML при импорте в Google Earth и Google Maps

### ISSUE THREAD

**Issue by Artyrm** [rendrom/rosreestr2coord#36]
Добрый день.
Спасибо за очень полезный инструмент.

При попытке работы с получающимися .kml обнаружил следующее:

1. При открытии в Google Earth полигон не отображается. Причина оказалась в том, что необходимо использовать `<outerBoundaryIs>` в случае если у полигона только внешний периметр (сейчас используется `<innerBoundaryIs>`).

2. При импорте в Google Maps происходит сбой "неверный формат". Причина оказалась в том, что нужно использовать в заголовке `<?xml version='1.0' encoding="UTF-8"?>`, тогда как сейчас используется `<?xml version='1.0' encoding='utf8'?>`. И имеет смысл наверное использовать кавычки тут всюду всё же, для единообразия.

**Comment by rendrom** [comment]
Привет! 
Спасибо за сообщение об ошибке экспорта в KML. 
Внес необходимые изменения.
Прошу проверить, что экспорт в последней версии из master работает корректно для Google Maps, и можно закрывать баг.

Я проверил в браузерной версии Google Earth и QGIS.

![Screenshot 2020-07-07 at 10 43 01](https://user-images.githubusercontent.com/1478481/86696009-a449e400-c03f-11ea-82bc-01abc4e80d8a.png)

**Comment by Artyrm** [comment]
Кажется, я что-то не то делаю.

`python setup.py install` нормально отработало, `rosreestr2coord.exe` имеет акутальную дату (кстати, наверное, функционал --version не помешает), однако делает всё по-старому. 

В папке модулей при этом появилась отдельная папка с новой версией (4.0.9):
![image](https://user-images.githubusercontent.com/21180686/86751098-196ce780-c047-11ea-95d1-d25494ebb093.png)

**Comment by rendrom** [comment]
Я пока не обновлял номер версии

Чтобы проверить изменения нужно получить последнюю версию из репозитория и установить локально все зависимости в виртуальное окружение, затем запустить скрипт командой python -m rosreestr2coord -c КАДАСТРОВЫЙ_НОМЕР

Вот новый файл который получается при экспорте в KML, если с ним всё хорошо, поднимаю версию и заливаю в pip

[38_36_000021_1106.kml.zip](https://github.com/rendrom/rosreestr2coord/files/4885609/38_36_000021_1106.kml.zip)

**Comment by Artyrm** [comment]
Да, я конечно же загрузил последнюю, убедился что это точно файлы с изменениями. А потом попытался с помощью `python setup.py install` его собрать и установить в модули\скрипты. Причём с виду всё отрабатывало нормально - нужные файлы вроде бы копировались и собирались, дата на .exe файле обновилась, но функционал нет. Попробовал запускать как модуль через `python -m`, тоже самое. Потом я поинтересовался, что с модулем, оказалось, файлы *.py в папке питона старые. При этом появилась некая новая _egg папка. Словом, я немного потерялся в происходящем :)

Файл kml загрузил - в Google Maps открывается, всё нормально.

**Comment by rendrom** [comment]
Выпустил новую версию `4.0.10`. Фикс с KML и добавил`-v` опцию консоли
