### ISSUE TITLE
Install error on MacOS

### ISSUE THREAD

**Issue by orean** [rendrom/rosreestr2coord#37]
Получаю ошибку при попытке установки на MacOS
`$ pip install rosreestr2coord
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting rosreestr2coord
  Downloading https://files.pythonhosted.org/packages/2b/60/69c7e02216d1bb2a4c12035f4f47e97a17f1e902933a1d3d108f3f738993/rosreestr2coord-4.0.10.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wp/q5xdq79941n1d38vgwtk48yr0000gn/T/pip-install-KFddN7/rosreestr2coord/setup.py'"'"'; __file__='"'"'/private/var/folders/wp/q5xdq79941n1d38vgwtk48yr0000gn/T/pip-install-KFddN7/rosreestr2coord/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/wp/q5xdq79941n1d38vgwtk48yr0000gn/T/pip-install-KFddN7/rosreestr2coord/pip-egg-info
         cwd: /private/var/folders/wp/q5xdq79941n1d38vgwtk48yr0000gn/T/pip-install-KFddN7/rosreestr2coord/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wp/q5xdq79941n1d38vgwtk48yr0000gn/T/pip-install-KFddN7/rosreestr2coord/setup.py", line 5, in <module>
        from rosreestr2coord.version import VERSION
      File "rosreestr2coord/__init__.py", line 1, in <module>
        from rosreestr2coord.parser import Area
      File "rosreestr2coord/parser.py", line 9, in <module>
        from rosreestr2coord.merge_tiles import PkkAreaMerger
      File "rosreestr2coord/merge_tiles.py", line 175
        end='')
           ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

вручную
`$ git clone https://github.com/rendrom/rosreestr2coord
Cloning into 'rosreestr2coord'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 950 (delta 32), reused 30 (delta 10), pack-reused 890
Receiving objects: 100% (950/950), 432.83 KiB | 288.00 KiB/s, done.
Resolving deltas: 100% (574/574), done.
~ $ cd ./rosreestr2coord
rosreestr2coord $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from rosreestr2coord.version import VERSION
  File "/Users/orean/rosreestr2coord/rosreestr2coord/__init__.py", line 1, in <module>
    from rosreestr2coord.parser import Area
  File "/Users/orean/rosreestr2coord/rosreestr2coord/parser.py", line 9, in <module>
    from rosreestr2coord.merge_tiles import PkkAreaMerger
  File "/Users/orean/rosreestr2coord/rosreestr2coord/merge_tiles.py", line 175
    end='')
       ^
SyntaxError: invalid syntax`

**Comment by rendrom** [comment]
Библиотека rosreestr2coord совместима только с Python3. 
Поддержка Python2 была в версии 1.x,вот последний коммит https://github.com/rendrom/rosreestr2coord/commit/6ffbad3c6573cbf732caeb3b372d0faac03328bf

**Comment by orean** [comment]
Спасибо!
