### ISSUE TITLE
Помогите пожалуйста

### ISSUE THREAD

**Issue by larhai** [rendrom/rosreestr2coord#38]
C:\rosreestr2coord>rosreestr2coord -m 03:24:022604:20
Press Ctrl+C to exit
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", l
ine 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", l
ine 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\Scripts\rosreest
r2coord.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-package
s\rosreestr2coord\console.py", line 144, in console
    run_console(opt)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-package
s\rosreestr2coord\console.py", line 83, in run_console
    f = open(opt.list, 'r')
OSError: [Errno 22] Invalid argument: '03:24:022604:20'

**Comment by rendrom** [comment]
если установка через `pip install rosreestr2coord ` то нужная команда будет такая
```bash
rosreestr2coord -c 03:24:022604:20
```

`-m` используется для запуска скрипта из директории проекта если установка через venv, тогда команда такая

```bash
rosreestr2coord -m -c 03:24:022604:20
```

**Comment by rendrom** [comment]
![Figure_1](https://user-images.githubusercontent.com/1478481/88811800-9411c880-d1e9-11ea-9fa4-0a291d27902c.png)

**Comment by larhai** [comment]
А сами значения координат как получить?

**Comment by rendrom** [comment]
Извлечь из экспортируемого geojson или kml файла. Можно использовать эти файлы практически в любой ГИС. Можете загрузить их в QGIS. Geojson можно открыть в тестовом редакторе.

**Comment by rendrom** [comment]
Получилось? Если есть идеи по улучшению, буду рад ознакомиться.
