### ISSUE TITLE
Пакет не устанавливается

### ISSUE THREAD

**Issue by drnextgis** [rendrom/rosreestr2coord#4]
Пакет не устанавливается, поскольку возникает ошибка:

```
$ pip install -e ./rosreestr2coord
Obtaining file:///home/rykov/git/rr2crd/rosreestr2coord
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rykov/git/rr2crd/rosreestr2coord/setup.py", line 4, in <module>
        from scripts.parser import VERSION
      File "scripts/parser.py", line 13, in <module>
        from scripts.merge_tiles import PkkAreaMerger
      File "scripts/merge_tiles.py", line 12, in <module>
        from PIL import Image
    ImportError: No module named PIL
```

Установщик просто не доходит до запуска функции `setup`, в которой указаны необходимые зависимости, а падает на этапе импорта. Довольно странный подход к определению версии пакета, надо бы переделать.

**Comment by drnextgis** [comment]
А [тут](https://github.com/rendrom/rosreestr2coord/blob/54e6028a3890e81d4552f2fac3f199e39f82fac9/setup_gui.py#L3)?

**Comment by rendrom** [comment]
так до ума и не довёл установку для пользовательского интерфейса. Хотел сделать сборку при помощи cx_Freeze, но вываливается с ошибками. Поэтому пока это отложил, а setup_gui.py нерабочий. 
Буду признателен, если подскажите как можно сделать инсталлятор этого приложения, да так, чтобы внутри был ещё и OpenCV
