### ISSUE TITLE
Земельные участки ЕЗП

### ISSUE THREAD

**Issue by stolyar92** [rendrom/rosreestr2coord#46]
Инструмент не позволяет определять участки ЕЗП, так как они идут без границ и обработка просто пропускает их.
Мне помогла модификация класса Area(). Не силен в программировании, так что заранее извиняюсь, если это "г*внокод")))
class Area(), после:
`
feature_info = self.download_feature_info()
`
я добавил:
`
if feature_info:
            if feature_info['attrs']['parcel_type'] == 'parcel_ez':
                self.center_only = True
            elif feature_info['attrs']['parcel_type'] != 'parcel_ez':
                self.get_geometry()
`
Тут я проверяю тип земельного участка **parcel_type** и если он равен **parcel_ez** - применяю логику **center_only = True**, так как она не пытается определить границы участка. Дальше уже в пользовательской функции определяю логику определения и загрузки связанных участков. API ссылка для получения связанный участков:
`
https://pkk.rosreestr.ru/api/features/1?_=1613660910132&text={{ cn }}%2F*&limit=40&skip=0
`
где {{ cn }} - участок ЕЗП

Думаю, что стоит рассмотреть добавление функциональности по загрузки участков ЕЗП в виде функции класса

Заранее благодарен)

**Comment by rendrom** [comment]
Загрузить только центры участков можно при помощи ключа `-C`

`python -m rosreestr2coord -C -c [кадастровый номер]`
