### ISSUE TITLE
Выгрузка периметра квартала

### ISSUE THREAD

**Issue by tarleproton** [rendrom/rosreestr2coord#49]
Привет! Спасибо за отличный проект! Но похоже сейчас ты его не поддерживаешь, но все же)  Не выходит выгрузить координаты периметра кварталов, может подскажешь в чем дело? На выходе получается только координата центра квартала. Может дело в изображении с которого получаем контур?

**Comment by rendrom** [comment]
Привет! Самое смешное в этом проекте, что я сам им никогда не пользовался. Сделал для спортивного интереса. Сейчас у росреестра на карте обновились технологии на векторные тайлы и можно попробовать зайти с другой стороны на извлечение координат. 
А какой квартал не загружается? Или все?

**Comment by tarleproton** [comment]
Ещё раз привет! Хороший спортивный интерес, просто отличный!  Все кварталы .  При загрузки квартала, изображение не корректное, просто фон, без контуров( Наверное в этом затык. 
 С участками все работает. Пробовал сам разбираться, подгружал изображения с росреестра и брал от туды xmin, xmax, ymin, ymax. Фигура квартала отображалась корректно, но точности координат не было. Потом посмотрел , что у тебя xmin, xmax, ymin, ymax и изображение подгружаются немного иначе. Подставил твои изображения и xmin, xmax, ymin, ymax все сработало корректно.

**Comment by rendrom** [comment]
Вообще это старая ошибка #45 ещё не удалось найти подходящие параметры для всех случаев,
Сейчас залил новую версию которая работает по участкам и кварталам (из моего списка проверки)

**Comment by tarleproton** [comment]
Спасибо, за поддержку проекта! Все сработало! Очень благодарен! Если это спортивный интерес боюсь представить в чем же заключается твоя работа)
