### ISSUE TITLE
Изменения легенды/символогии (отсутствие границ кадастровых участков)

### ISSUE THREAD

**Issue by MrChebur** [rendrom/rosreestr2coord#50]
Судя по всему на ПКК поменяли легенду и теперь земельные участки не имеют границ (вообще не прорисовываются).
В том числе и на официальном сайте. Соответственно библиотека не работает.

Надеюсь это временно.

![firefox_KQCryhEVMX](https://user-images.githubusercontent.com/20655102/129547435-70cf1df6-dd8d-4dfc-95ab-5c4987220040.png)

![firefox_qwUyKpAmWX](https://user-images.githubusercontent.com/20655102/129547440-bf23a6b5-baca-4f69-99fc-eab5a9ddfca6.png)

**Comment by rendrom** [comment]
На сайте публичной кадастровой карты в консоли валятся ошибки
![image](https://user-images.githubusercontent.com/1478481/129557339-097599b5-9aab-48fe-9afc-b3f1fd24b2be.png)
Скорее всего, у них какой-то сбой. Возможно, грядёт какое-то обновление с новыми ограничениями

**Comment by MrChebur** [comment]
@rendrom Спасибо, направил в заявку в тех. поддержку. Посмотрим, что ответят.

**Comment by stolyar92** [comment]
Вроде ожил

**Comment by MrChebur** [comment]
Ожил
