### ISSUE TITLE
Обработка ЗОУИТ в формате 02:52-6.667

### ISSUE THREAD

**Issue by sbgeomap** [rendrom/rosreestr2coord#53]
Как будто поменялся формат реестровых номеров для ЗОУИТ
программа вылетает с ошибками и, на сколько я понял, жалуется на двоеточие и тире

**Comment by rendrom** [comment]
В новую версию внесены изменения чтобы ЗОУИТ грузились в формате 02:52-6.667

`rosreestr2coord -с 02:52-6.667 -t 10 -P `

Прошу протестировать и закрыавть этот тикет

![image](https://user-images.githubusercontent.com/1478481/141149863-cd9129e8-5210-4c8c-a507-8f1a45dd03f3.png)

**Comment by sbgeomap** [comment]
Протестировал два ЗОУИТ - не скачивает тайлы до конца

C:\Users\User1>rosreestr2coord -t 10 -c 02:15-6.426 -P
Press Ctrl+C to exit
Start downloading area info: https://pkk.rosreestr.ru/api/features/10/02:15-6.426
Area info downloaded.
Get tiles:
97% 47/48
Completed, 47 tiles received

C:\Users\User1>rosreestr2coord -t 10 -c 02:17-6.374 -P
Press Ctrl+C to exit
Start downloading area info: https://pkk.rosreestr.ru/api/features/10/02:17-6.374
Area info downloaded.
Get tiles:
98% 55/56
Completed, 55 tiles received

**Comment by sbgeomap** [comment]
Сегодня всё отлично работает.
Спасибо!
