### ISSUE TITLE
Ошибка пакетной загрузки Windows

### ISSUE THREAD

**Issue by amoudaria** [rendrom/rosreestr2coord#54]
При вводе
 rosreestr2coord -l list_example.txt 
в командной строке на Windows выбивает ошибку о том, что нет подобных команд в библиотеке -l list_example.txt

**Comment by anlarina21** [comment]
![Снимок экрана 2021-11-02 164312](https://user-images.githubusercontent.com/93597106/139861345-62f69a3b-a08a-404e-8eb9-5f0c12dbc0b9.jpg)
![Снимок экрана 2021-11-02 164755](https://user-images.githubusercontent.com/93597106/139861350-4dafdf68-9a2f-4251-b002-4c3ef294405f.jpg)
Также не работает  -l list_example.txt, при попытке сделать через -m вылезает ошибка, и ничего до конца не грузится...

**Comment by rendrom** [comment]
Понятно, спасибо за репорт. Там должен был быть ключ -l конечно же. Каким-то образом поменялся. Поотлаживаю. Можете список скинуть текстовый или десяток строк с номерами, пожалуйста?

**Comment by anlarina21** [comment]
> Понятно, спасибо за репорт. Там должен был быть ключ -l конечно же. Каким-то образом поменялся. Поотлаживаю. Можете список скинуть текстовый или десяток строк с номерами, пожалуйста?

[trypart.txt](https://github.com/rendrom/rosreestr2coord/files/7461320/trypart.txt)

буду очень ждать!

**Comment by stolyar92** [comment]
После загрузки участка:
`Type Error! the JSON object must be str, bytes or bytearray, not bool`
Тайлы прилетают пустые.

**Comment by rendrom** [comment]
> Попробовал rostreestrcoord -h, увидел что можно пакетную загрузку через rosreestr2coord -m list_example.txt делать, в командной строке пишется, что все 3 координаты получены, однако в результатах видно только 2 первых файла

Нужны подробности, у меня по этому списку все три участка
![image](https://user-images.githubusercontent.com/1478481/141131124-ecf99737-176c-4d61-954b-aa4116db0a12.png)

**Comment by rendrom** [comment]
> ![Снимок экрана 2021-11-02 164312](https://user-images.githubusercontent.com/93597106/139861345-62f69a3b-a08a-404e-8eb9-5f0c12dbc0b9.jpg) ![Снимок экрана 2021-11-02 164755](https://user-images.githubusercontent.com/93597106/139861350-4dafdf68-9a2f-4251-b002-4c3ef294405f.jpg) Также не работает -l list_example.txt, при попытке сделать через -m вылезает ошибка, и ничего до конца не грузится...

спсиок должен быть в одну колонку
