### ISSUE TITLE
Unexpected result for 40:14:0:705

### ISSUE THREAD

**Issue by kgv** [rendrom/rosreestr2coord#57]
Request: 40:14:0:705 (`rosreestr2coord -c 40:14:000000:705`)

Result is the single polygon with coordinates: 36.02516797742755,55.10458670706924 36.02500628067641,55.1044582297623 36.02515899427471,55.104499342545466 36.02516797742755,55.10458670706924 36.02516797742755,55.10458670706924

Expected multiple poligons.

Version: 4.0.19 (from pip)

---

Запрос: 40:14:0:705 (`rosreestr2coord -c 40:14:000000:705`)

Результатом является одиночный полигон с координатами: 36.02516797742755,55.10458670706924 36.02500628067641,55.1044582297623 36.02515899427471,55.104499342545466 36.02516797742755,55.10458670706924 36.02516797742755,55.10458670706924

Должен быть мультиполигон.

Версия: 4.0.19 (установлена из pip)

**Comment by rendrom** [comment]
У меня вот такое загрузилось
![image](https://user-images.githubusercontent.com/1478481/151763168-33c1b790-6b90-455a-8254-a88791377259.png)

**Comment by kgv** [comment]
да, это похоже на верные полигоны, вероятно это проблема на моей стороне, буду разбираться

**Comment by rendrom** [comment]
Попробуйте с ключом -P
Если какие-то ошибки вываливаются, присылайте скриншоты или логи. 
Геометрия не должна была начать формироваться пока все тайлы не загрузились
