### ISSUE TITLE
Как получить geojson для КУ с дробью (16:07:160001:1180/4) ?

### ISSUE THREAD

**Issue by SuperTone** [rendrom/rosreestr2coord#65]
Как получить geojson для КУ 16:07:160001:1180/4 ?
`rosreestr2coord -e 1 -r -c 16:07:160001:1180/4`
В результате получаю лишь
`100% 1/1`
`Completed, 1 tile received`
`raster - /root/tmp/16_7_160001_1180/4/1000_1000/0_0.png`
В чем может быть проблема?

**Comment by rendrom** [comment]
Такой номер не учитывается при формировании запросов. Добавлю проверку. 
Если есть возможность, напишите, пожалуйста, какие варианты номеров могут быть в тикете #64

**Comment by SuperTone** [comment]
На сайте https://pkk.rosreestr.ru параметр  "Layer Definitions" выгладит так, через contour_num
`{"8":"id = '16:7:160001:1180' and contour_num = 4","9":"id = '16:7:160001:1180' and contour_num = 4"}`

а rosreestr2coord пытается получить данные используя параметр Layer Definitions с дробью
`{'0': "ID = '16:7:160001:1180/3'", '1': "ID = '16:7:160001:1180/3'", '2': "ID = '16:7:160001:1180/3'", '3': "ID = '16:7:160001:1180/3'", '4': "ID = '16:7:160001:1180/3'", '5': "ID = '16:7:160001:1180/3'", '6': "ID = '16:7:160001:1180/3'", '7': "ID = '16:7:160001:1180/3'", '8': "ID = '16:7:160001:1180/3'", '9': "ID = '16:7:160001:1180/3'", '10': "ID = '16:7:160001:1180/3'", '11': "ID = '16:7:160001:1180/3'", '12': "ID = '16:7:160001:1180/3'", '13': "ID = '16:7:160001:1180/3'", '14': "ID = '16:7:160001:1180/3'", '15': "ID = '16:7:160001:1180/3'", '16': "ID = '16:7:160001:1180/3'", '17': "ID = '16:7:160001:1180/3'", '18': "ID = '16:7:160001:1180/3'", '19': "ID = '16:7:160001:1180/3'", '20': "ID = '16:7:160001:1180/3'"}`

я думаю что в этом может быть дело.

про #64 я не понял что требуется(

**Comment by rendrom** [comment]
@SuperTone спасибо за репорт и исследование способа решения. Залил новую версию 4.1.5 с доработками. Прошу протестировать и закрывать тикет.

Так получилось, что я сам никогда не пользовался этим скриптом и даже не знаю какие варианты кадастровых номеров могут встречаться. Поэтому вношу доработки после таких вот баг-репортов. Если есть возможность как-то структурировать информацию по правилам формирования кадастровых номеров, прошу прокомментировать в тикете #64

**Comment by SuperTone** [comment]
@rendrom спасибо за оперативную доработку. Теперь КУ с дробью срабатывают.
