### ISSUE TITLE
ошибка при загрузке 

### ISSUE THREAD

**Issue by anettapik** [rendrom/rosreestr2coord#73]
Добрый день! 
![image](https://user-images.githubusercontent.com/120940816/217255718-319f7d44-6865-4a44-a46e-525ef916bf67.png)
Возникает такая ошибка при загрузке

**Comment by rendrom** [comment]
Попробуйте добавить `-P`

**Comment by anettapik** [comment]
Спасибо! Это помогло
А у меня ещё вопрос , как я могу скачать все участки на территорию
Санкт-Петербурга?

Вт, 7 февр. 2023 г. в 16:45, Artemiy ***@***.***>:

**Comment by rendrom** [comment]
Такой возможности в скрипте не предусмотрено.
