### ISSUE TITLE
Результат работы скрипта не соответствует информации в кадастровой выписке

### ISSUE THREAD

**Issue by AndrewKirikoff** [rendrom/rosreestr2coord#77]
Подскажите пожалуйста. В описание к скрипту написано, что Результат работы скрипта не соответствует информации в кадастровой выписке. Это получается что все координаты участков не соответствуют ? Получается смысла использовать этот скрипт нет если надо получить участок, могут быть проблемы с пересечением и выходом за какие-либо границы?

**Comment by rendrom** [comment]
Привет! Извиняюсь, что отвечаю только сейчас. Скрипт действительно может давать неточные координаты по сравнению с кадастровой выпиской, но он все же полезен для задач, где не требуется абсолютная точность. Это быстрый способ очертить примерные границы участка, что подходит для предварительной оценки и планирования.
