### ISSUE TITLE
Добавить перезагрузку кадастрового номера 

### ISSUE THREAD

**Issue by TSA21432** [rendrom/rosreestr2coord#78]
Доброго дня!
Повторить загрузку кадастрового номера который был пропущен с ответом сервера 
ERROR:rosreestr2coord.logger:<urlopen error [WinError 10061]
при пакетной загрузке из файла

возможно ли запустить пакетную загрузку в многопотоковом режиме?
Спасибо!

**Comment by TSA21432** [comment]
https://disk.yandex.ru/i/pT15N33BCPGaQQ
я про такое

**Comment by rendrom** [comment]
ПРиношу извинения, что отвечаю только сейчас. Многопоточность в пакетной загрузке не предусмотрена.
