### ISSUE TITLE
Дублирует участки

### ISSUE THREAD

**Issue by denny123** [rendrom/rosreestr2coord#8]
При запросе например номера 60:18:0060201:3306, png как надо, а вот координаты участков в geojson дублирует и в результате получаются дырки вместо участков. Также хотел узнать про точность(вроде параметр -e), как им пользоваться(на данном участке также не все точки видит)?

**Comment by denny123** [comment]
export.py

           for fry in range(len(coords)):
                for j in range(len(coords[fry])):
                    xy = coords[fry][j]
                    xy.append(xy[0])
                close_xy.append(xy)    <------------------------подвинул тут влево
            multi_polygon.append(close_xy)   <-----------------------и тут влево
            feature = {"type": "Feature",

вроде как помогло, требуется визирование автора)

**Comment by rendrom** [comment]
@denny123 хорошо что заметили, спасибо. Предлагаю отправить Pull Request с изменениями

**Comment by denny123** [comment]
Я ничем не против, знать бы что это такое Pull Request(гитхаб не юзаю).

**Comment by rendrom** [comment]
Там вверху есть кнопка Fork, как нажмёшь, в твоём профиле будет копия репозитория, 

- клонируешь её к себе на компьютер git clone [название репозитория];
- вносишь изменения;
- сохраняешь git commit -a -m '#8 message' (#8 - номер этого бага, message - название коммита, короткий список изменений не более 80 символов)
- заливаешь к себе в форк git push origin master
- в интерфесе github нажимаешь Create Pull Request на странице своего форка этого репозитория.


Это всё для того чтобы сохранить авторстов твоих изменений в проекте. Если не хочется этим заниматься, могу я поправить и накатить

**Comment by denny123** [comment]
не не не, не надо мне авторства, правь сам, даю согласие и все права)

**Comment by rendrom** [comment]
параметр -e увеличивает точность распознавания угловых точек с изображения участка. 

https://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html 
epsilon – Parameter specifying the approximation accuracy. This is the maximum distance between the original curve and its approximation.

Для увелечения точности определения координат нет специального параметра, но в коде можно поменять значения параметра tile_size
https://github.com/rendrom/rosreestr2coord/blob/master/scripts/merge_tiles.py#L315

**Comment by denny123** [comment]
менял tile_size - ничего не изменилось, как будто он берет из другого места...

**Comment by rendrom** [comment]
Проверю. Это только для больших участков работает. Но точность все равно будет приблизительной при любых настройках.

**Comment by denny123** [comment]
я все на этом 60:18:0060201:3306 экспериментирую, там верхний участок и у него верхний правый угол с изгибом должен быть.....я там кстати баг создал уже по пакетной аппроксимации...

**Comment by denny123** [comment]
на счет точности, лучше просто сделать тайлы для заданных приближений, будет точность как в росреестре)

**Comment by rendrom** [comment]
Спасибо, обязательно поправлю как доберусь до компьютера
