### ISSUE TITLE
Погрешность координат

### ISSUE THREAD

**Issue by Li76ya** [rendrom/rosreestr2coord#84]
Доброго времени суток! Подскажите, пожалуйста, какая у координат участка погрешность? В "м" или в "см" ? Есть ли у вас данные на этот вопрос ?

**Comment by rendrom** [comment]
Погрешность может быть очень высокая. Сравнивать с реальными координатами мне не приходилось. Поэтому не могу сказать на сколько координаты могут отличаться.

**Comment by Li76ya** [comment]
Спасибо за ответ! 
На чем же тогда основывается предположение, что погрешность может быть очень высокая?

**Comment by rendrom** [comment]
На том, какие методы используются для извлечения координат участка.
Точность получаемой геометрии зависит от площади и сложности конфигурации исходной территории. 
Но даже если это будет прямоугольный участок на 10 соток, на результат работы этого скрипта не следует полагаться для выполнении каких-либо важных вычислений.

**Comment by Li76ya** [comment]
Понятно, спасибо!
