### ISSUE TITLE
Ошибки сертификата при попытке получить данные

### ISSUE THREAD

**Issue by YungIshimura** [rendrom/rosreestr2coord#87]
Добрый день. При попытке получения данных получаю ошибку.
![image](https://github.com/user-attachments/assets/21cf4f04-3791-4c5e-a1cc-1a554787a69e)

Прокси не помогает.
![image](https://github.com/user-attachments/assets/75a8fb8f-ed58-4592-aab7-b9821996440b)

**Comment by albinail** [comment]
аналогично "Start downloading area info: https://pkk.rosreestr.ru/api/features/1/38:6:144003:4723
[SSL: TLSV1_ALERT_DECODE_ERROR] tlsv1 alert decode error (_ssl.c:1007)"

**Comment by albinail** [comment]
![image](https://github.com/user-attachments/assets/083d9183-d227-43d2-bc1b-56d990c08cc2)
в колабе: Start downloading area info: https://pkk.rosreestr.ru/api/features/1/38:6:144003:4723
ERROR:rosreestr2coord.logger:Request failed: <urlopen error timed out>
timed out

**Comment by RomanBespalov** [comment]
> Добрый день. При попытке получения данных получаю ошибку. ![image](https://private-user-images.githubusercontent.com/83189636/368912076-21cf4f04-3791-4c5e-a1cc-1a554787a69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTAyMjksIm5iZiI6MTcyNjgwOTkyOSwicGF0aCI6Ii84MzE4OTYzNi8zNjg5MTIwNzYtMjFjZjRmMDQtMzc5MS00YzVlLWExY2MtMWE1NTQ3ODdhNjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNmZmNjU4OGJiYTI4NGUyM2VjODg2ZDA2NGQ3ZGI2N2QwMmY5YmQyYTE4ZGU4YzNkY2Q2OGIwODUxY2JkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ql8oQBo5ESLLlwbo2z02eWvCLoag4BMrF1qzGWyD6D8)
> 
> Прокси не помогает. ![image](https://private-user-images.githubusercontent.com/83189636/368912670-75a8fb8f-ed58-4592-aab7-b9821996440b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTAyMjksIm5iZiI6MTcyNjgwOTkyOSwicGF0aCI6Ii84MzE4OTYzNi8zNjg5MTI2NzAtNzVhOGZiOGYtZWQ1OC00NTkyLWFhYjctYjk4MjE5OTY0NDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjllOTVlNWFlMWU0YzhmOGE1ZjRkYjgxNzcwZWQxZTg2YmYyM2VhYWQ5ODQyYmEzOWNkN2ZmZTFlNDFkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._0FrXX0mvj7LKAWTiePY2VYhddDHNM2BFVSIYyMpMtw)

https://github.com/rendrom/rosreestr2coord/issues/72#issuecomment-2362843205

**Comment by andponom** [comment]
Опытным путём выяснили, что запросы продолжают исполняться в среде 3.9 и ранее. Начиная с 3.10 лезет эта ошибка.

**Comment by rendrom** [comment]
> > Добрый день. При попытке получения данных получаю ошибку. ![image](https://private-user-images.githubusercontent.com/83189636/368912076-21cf4f04-3791-4c5e-a1cc-1a554787a69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTAyMjksIm5iZiI6MTcyNjgwOTkyOSwicGF0aCI6Ii84MzE4OTYzNi8zNjg5MTIwNzYtMjFjZjRmMDQtMzc5MS00YzVlLWExY2MtMWE1NTQ3ODdhNjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNmZmNjU4OGJiYTI4NGUyM2VjODg2ZDA2NGQ3ZGI2N2QwMmY5YmQyYTE4ZGU4YzNkY2Q2OGIwODUxY2JkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ql8oQBo5ESLLlwbo2z02eWvCLoag4BMrF1qzGWyD6D8)
> > Прокси не помогает. ![image](https://private-user-images.githubusercontent.com/83189636/368912670-75a8fb8f-ed58-4592-aab7-b9821996440b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTAyMjksIm5iZiI6MTcyNjgwOTkyOSwicGF0aCI6Ii84MzE4OTYzNi8zNjg5MTI2NzAtNzVhOGZiOGYtZWQ1OC00NTkyLWFhYjctYjk4MjE5OTY0NDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjllOTVlNWFlMWU0YzhmOGE1ZjRkYjgxNzcwZWQxZTg2YmYyM2VhYWQ5ODQyYmEzOWNkN2ZmZTFlNDFkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._0FrXX0mvj7LKAWTiePY2VYhddDHNM2BFVSIYyMpMtw)
> 
> Привет, здесь написал, как решил - [#72 (comment)](https://github.com/rendrom/rosreestr2coord/issues/72#issuecomment-2362843205)

@RomanBespalov спасибо за раешение. Выпустил новую версию с переделанной системой запросов. Но флаг -P пока не удалось вернуть. Нужно искать другие варианты проксирования.

**Comment by skemaikin** [comment]
Доброго времени!
Есть еще один способ решения проблемы. Правда, он связан с использованием сертификата. Для файла `utils.py` в методе `perform_request`  следует использовать контекст:
```
context = ssl.create_default_context()
context.set_ciphers('DEFAULT@SECLEVEL=1')
context.minimum_version = ssl.TLSVersion.TLSv1_2
context.load_verify_locations('cacert.pem')
```
Сертификаты можно скачать, например, отсюда: https://www.gosuslugi.ru/crt

**Comment by rendrom** [comment]
> Доброго времени! Есть еще один способ решения проблемы. Правда, он связан с использованием сертификата. Для файла `utils.py` в методе `perform_request` следует использовать контекст:
> 
> ```
> context = ssl.create_default_context()
> context.set_ciphers('DEFAULT@SECLEVEL=1')
> context.minimum_version = ssl.TLSVersion.TLSv1_2
> context.load_verify_locations('cacert.pem')
> ```
> 
> Сертификаты можно скачать, например, отсюда: https://www.gosuslugi.ru/crt

Но это всё равно не решит проблемы с блокировкой по IP при превышении лимитов запросов.

**Comment by skemaikin** [comment]
> > Доброго времени! Есть еще один способ решения проблемы. Правда, он связан с использованием сертификата. Для файла `utils.py` в методе `perform_request` следует использовать контекст:
> > ```
> > context = ssl.create_default_context()
> > context.set_ciphers('DEFAULT@SECLEVEL=1')
> > context.minimum_version = ssl.TLSVersion.TLSv1_2
> > context.load_verify_locations('cacert.pem')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Сертификаты можно скачать, например, отсюда: https://www.gosuslugi.ru/crt
> 
> Но это всё равно не решит проблемы с блокировкой по IP при превышении лимитов запросов.

В режиме проксёвой рулетки (перебор прокси-списка) - вроде решает. В `utils.py`:
```
def get_rosreestr_headers() -> Dict[str, str]:
    from fake_useragent import UserAgent
    return {
        "pragma": "no-cache",
        "referer": "https://pkk.rosreestr.ru/",
        "user-agent": UserAgent().random,
        "x-requested-with": "XMLHttpRequest",
    }

def perform_request(
    url: str,
    proxy_handler: Optional[urllib.request.ProxyHandler],
    logger: Optional[object],
    timeout: int,
) -> bytes:
    try:
        headers = get_rosreestr_headers()
        if proxy_handler:
            opener = urllib.request.build_opener(proxy_handler)
            urllib.request.install_opener(opener)
        request = Request(url, headers=headers)
        
        context = ssl.create_default_context()
        context.set_ciphers('DEFAULT@SECLEVEL=1')
        context.minimum_version = ssl.TLSVersion.TLSv1_2
        context.load_verify_locations('cacert.pem')

        with urlopen(request, context=context, timeout=timeout) as response:
            read = response.read()
        is_error = is_error_response(url, read)
        if is_error:
            raise Exception(is_error)
        return read
    except urllib.error.HTTPError as er:
        if er.code == 400:
            raise er
        else:
            raise Exception(f"HTTPError: {er}")
    except Exception as er:
        if logger:
            logger.error(f"Request failed: {er}")
        raise
```

**Comment by zdch26** [comment]
> Доброго времени! Есть еще один способ решения проблемы. Правда, он связан с использованием сертификата. Для файла `utils.py` в методе `perform_request` следует использовать контекст:
> 
> ```
> context = ssl.create_default_context()
> context.set_ciphers('DEFAULT@SECLEVEL=1')
> context.minimum_version = ssl.TLSVersion.TLSv1_2
> context.load_verify_locations('cacert.pem')
> ```
> 
> Сертификаты можно скачать, например, отсюда: https://www.gosuslugi.ru/crt

Похоже там проблема не столько в сертификате, сколько в поддержке набора шифров на стороне pkk.rosreestr.ru
С их стороны при TLS рукопожатии согласуется TLS_RSA_WITH_AES_256_CBC_SHA (возможно, и другие, но сути не поменяет), а он в актуальных сборках TLS библиотек не поддерживается, потому что уже считается слабым (https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_CBC_SHA/). Поэтому при их отсутсвии в Client Hello сервер сразу рвет соединение (decord error). 

В принципе, в utils.py достаточно будет одной строки, чтобы заработало
context.set_ciphers('ALL:@SECLEVEL=1')

![Screen Shot 2024-09-24 at 18 13 06](https://github.com/user-attachments/assets/27750a03-76ea-43f2-9604-6ea238abfd86)

**Comment by zdch26** [comment]
pkk.rosreestr.ru работает с TLS 1.2, но вот сами алгоритмы шифрования почему-то используются устаревшие. 
По поводу ошибки сертификата - подразумеваю, ему корневых не хватает на стороне клиента или игнорирования того, что он самоподписанный. 
Так работало:
```
context = ssl._create_unverified_context()
context.set_ciphers('ALL:@SECLEVEL=1')
```

**Comment by YungIshimura** [comment]
> > ```
> > context = ssl._create_unverified_context()
> > context.set_ciphers('ALL:@SECLEVEL=1')
> > ```
> 
> Точно так, работает!

Для версии 4.4.0 кажется работает! Спасибо.

**Comment by rendrom** [comment]
Всем спасибо за обсуждение и поиск способов исправления! Выпустил новую версию с ещё одной переработкой по этой проблеме.
