### ISSUE TITLE
Не работает прокси

### ISSUE THREAD

**Issue by denny123** [rendrom/rosreestr2coord#9]
Пока везде не проставил with_proxy=True(не разбираюсь в питоне) через прокси не шел.

**Comment by TSA21432** [comment]
не пойму как с ним работать
C:\Users\xxx>rosreestr2coord -c 22:02 -t3 -w -p
Press Ctrl+C to exit
usage: rosreestr2coord [-h] [-c CODE] [-t AREA_TYPE] [-p PATH] [-o OUTPUT]
                       [-w] [-l LIST] [-a] [-d] [-D DELAY] [-r] [-e EPSILON]
                       [-C] [-P]
rosreestr2coord: error: argument -p/--path: expected one argument

C:\Users\xxx>

**Comment by rendrom** [comment]
Попробуйте ввести `-P` а не `-p`
