### ISSUE TITLE
Ругается на parser 

### ISSUE THREAD

**Issue by Akarapidoz** [rendrom/rosreestr2coord#94]
Ругается на строку 133

**Comment by rendrom** [comment]
Добрый день! Пожалуйста, предоставьте больше сведений: какую команду вы выполняли и что содержится в ошибке.

**Comment by Akarapidoz** [comment]
f"TYPENAME={cad_item["className"]}", пишет что присутствует синтаксическая ошибка. Ругается на эти двойные кавычки "className". Такая ошибка появилась после обновления с версии 4.6.5 до версии 5.0

**Comment by rendrom** [comment]
Спасибо за обращение! Выпустил 5.0.1
Там сейчас сильно всё меняется в API поэтому возможны сбои
